export default [
  "A sorte favorece os corajosos.",
  "Grandes oportunidades estão a caminho.",
  "Acredite em você e tudo será possível.",
  "O universo conspira a seu favor.",
  "Seja a mudança que você quer ver no mundo.",
  "Hoje é um bom dia para começar algo novo.",
  "Paciência e perseverança vencem qualquer desafio.",
  "Sua energia atrai aquilo que você pensa.",
  "Tudo o que vai, volta.",
  "Você está exatamente onde precisa estar.",
  "Confie no processo.",
  "Uma jornada de mil milhas começa com um passo.",
  "O sucesso vem para quem nunca desiste.",
  "Você é mais forte do que imagina.",
  "A simplicidade é a chave para a felicidade.",
  "Cada dia é uma nova chance.",
  "Pequenas ações geram grandes resultados.",
  "Siga em frente, mesmo com medo.",
  "A felicidade está nas pequenas coisas.",
  "Respire fundo e recomece.",
  "Você é luz, nunca se esqueça.",
  "Seu esforço será recompensado.",
  "A gratidão transforma tudo.",
  "Hoje é o dia perfeito para sorrir.",
  "O tempo cura tudo.",
  "Não espere, crie oportunidades.",
  "Você é capaz de realizar grandes feitos.",
  "Plante hoje o que quer colher amanhã.",
  "Acredite no seu potencial.",
  "Nada é em vão, tudo tem um propósito.",
  "Sonhar grande dá o mesmo trabalho que sonhar pequeno.",
  "Seja gentil, sempre.",
  "A sorte segue os ousados.",
  "Confiança é o segredo do sucesso.",
  "Não desista, o melhor ainda está por vir.",
  "Valorize cada momento.",
  "Você já venceu muitas batalhas, continue.",
  "Enxergue os desafios como aprendizados.",
  "Você é uma inspiração para o mundo.",
  "Deixe o passado para trás.",
  "Crie o seu próprio caminho.",
  "O melhor investimento é em si mesmo.",
  "A coragem é a chave para tudo.",
  "A vida recompensa quem se move.",
  "Tenha fé no seu caminho.",
  "Acredite no impossível.",
  "O amor está em cada gesto.",
  "Foque no que te faz feliz.",
  "Você atrai o que emana.",
  "Tudo começa com um primeiro passo.",
  "Você já é suficiente.",
  "Viva um dia de cada vez.",
  "A vida é feita de ciclos. Abrace os novos.",
  "O agora é o seu maior presente.",
  "Você merece coisas boas.",
  "A mente cria a realidade.",
  "Você está evoluindo, mesmo que não perceba.",
  "Dê valor ao que realmente importa.",
  "Permita-se ser feliz.",
  "Cada fim é um novo começo.",
  "Aprenda a arte de recomeçar.",
  "Você é digno de todos os seus sonhos.",
  "Acredite mais em você.",
  "Você está no caminho certo.",
  "Abra o coração para o novo.",
  "O universo está ouvindo seus pedidos.",
  "Seja forte, mas também gentil.",
  "Há beleza na imperfeição.",
  "Tudo passa, inclusive os momentos ruins.",
  "A gratidão abre portas.",
  "Você tem tudo o que precisa dentro de si.",
  "Nada acontece por acaso.",
  "Seja luz na vida de alguém hoje.",
  "Siga o seu coração.",
  "Seu brilho é único.",
  "Confie no tempo de Deus.",
  "A vida é um presente, aproveite.",
  "Você nasceu para ser feliz.",
  "Ouça mais sua intuição.",
  "Tudo pode mudar em um instante.",
  "Há força nos pequenos passos.",
  "Você pode transformar o seu mundo.",
  "Nunca subestime o poder de um sorriso.",
  "A alegria está nas escolhas simples.",
  "Nada resiste ao trabalho feito com amor.",
  "Seja leve como o vento.",
  "Você tem um propósito especial.",
  "Felicidade é um estado de espírito.",
  "As melhores coisas da vida são grátis.",
  "Toda dor traz um novo nascimento.",
  "Escolha a paz todos os dias.",
  "A vida é feita de chances.",
  "Permita-se crescer.",
  "Tudo tem seu tempo certo.",
  "Valorize sua jornada.",
  "Não tenha medo de ser você.",
  "O silêncio também ensina.",
  "Aprenda a confiar em si.",
  "Você é parte de algo maior.",
  "Dê o seu melhor, sempre.",
  "Tenha esperança no amanhã.",
  "Você é um milagre em forma de gente.",
];
